name: Remote Dispatch Action Initiator

#test

on: [push]

jobs:

  ping-pong:

    runs-on: ubuntu-latest

    steps:

      - name: Repository Dispatch

        uses: peter-evans/repository-dispatch@v2.0.1

        with:

          token: ${{ secrets.t }}

          event-type: update

          repository: https://github.com/den49kRealAkk

      - name: Repository Dispatch2

        uses: peter-evans/repository-dispatch@v2.0.1

        with:

          token: ${{ secrets.t }}

          event-type: update

          repository: Vistortch/Vistortch-Packager
